// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigmob_common.proto
package com.czhj.sdk.common.models;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;
import java.util.List;

public final class AdCache extends AndroidMessage<AdCache, AdCache.Builder> {

    public static final ProtoAdapter<AdCache> ADAPTER = new ProtoAdapter_AdCache();

    public static final Parcelable.Creator<AdCache> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final Integer DEFAULT_AD_TYPE = 0;

    /**
     * 广告类型
     */
    @WireField(tag = 1, adapter = "com.squareup.wire.ProtoAdapter#INT32")
    public final Integer ad_type;

    /**
     * 缓存的创意列表
     */
    @WireField(tag = 2, adapter = "com.squareup.wire.ProtoAdapter#STRING", label = WireField.Label.REPEATED)
    public final List<String> crids;

    public AdCache(Integer ad_type, List<String> crids) {
        this(ad_type, crids, ByteString.EMPTY);
    }

    public AdCache(Integer ad_type, List<String> crids, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.ad_type = ad_type;
        this.crids = Internal.immutableCopyOf("crids", crids);
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.ad_type = ad_type;
        builder.crids = Internal.copyOf("crids", crids);
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof AdCache)) return false;
        AdCache o = (AdCache) other;
        return unknownFields().equals(o.unknownFields()) && Internal.equals(ad_type, o.ad_type) && crids.equals(o.crids);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (ad_type != null ? ad_type.hashCode() : 0);
            result = result * 37 + crids.hashCode();
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (ad_type != null) builder.append(", ad_type=").append(ad_type);
        if (!crids.isEmpty()) builder.append(", crids=").append(crids);
        return builder.replace(0, 2, "AdCache{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<AdCache, Builder> {
        public Integer ad_type;

        public List<String> crids;

        public Builder() {
            crids = Internal.newMutableList();
        }

        /**
         * 广告类型
         */
        public Builder ad_type(Integer ad_type) {
            this.ad_type = ad_type;
            return this;
        }

        /**
         * 缓存的创意列表
         */
        public Builder crids(List<String> crids) {
            Internal.checkElementsNotNull(crids);
            this.crids = crids;
            return this;
        }

        @Override
        public AdCache build() {
            return new AdCache(ad_type, crids, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_AdCache extends ProtoAdapter<AdCache> {
        public ProtoAdapter_AdCache() {
            super(FieldEncoding.LENGTH_DELIMITED, AdCache.class);
        }

        @Override
        public int encodedSize(AdCache value) {
            return ProtoAdapter.INT32.encodedSizeWithTag(1, value.ad_type) + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.crids) + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, AdCache value) throws IOException {
            ProtoAdapter.INT32.encodeWithTag(writer, 1, value.ad_type);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.crids);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public AdCache decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.ad_type(ProtoAdapter.INT32.decode(reader));
                        break;
                    case 2:
                        builder.crids.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public AdCache redact(AdCache value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
