// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigmob_common.proto
package com.czhj.sdk.common.models;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;
import java.util.List;

public final class User extends AndroidMessage<User, User.Builder> {
    public static final ProtoAdapter<User> ADAPTER = new ProtoAdapter_User();

    public static final Parcelable.Creator<User> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final Integer DEFAULT_YOB = 0;

    public static final String DEFAULT_GENDER = "";

    public static final Boolean DEFAULT_IS_MINOR = false;

    public static final Boolean DEFAULT_DISABLE_PERSONALIZED_RECOMMENDATION = false;

    public static final Boolean DEFAULT_CHANGE_RECOMMENDATION_STATE = false;

    /**
     * 生日年份，例：1995
     */
    @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#UINT32"
    )
    public final Integer yob;

    /**
     * 性别，M-男；F-女；O-未知
     */
    @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#STRING"
    )
    public final String gender;

    /**
     * 用户已安装应用列表
     */
    @WireField(
            tag = 3,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.REPEATED
    )
    public final List<String> app_list;

    /**
     * 用户属性id，如：3342，表示改用户安装了com.weibo应用；1111，表示该用户是体育运动爱好者
     */
    @WireField(
            tag = 4,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.REPEATED
    )
    public final List<String> user_strategy;

    /**
     * 设备应用市场版本号
     */
    @WireField(
            tag = 5,
            adapter = "Version#ADAPTER"
    )
    public final Version app_market_version;

    /**
     * 是否未成年人，false-否；true-是
     */
    @WireField(
            tag = 7,
            adapter = "com.squareup.wire.ProtoAdapter#BOOL"
    )
    public final Boolean is_minor;

    /**
     * 是否禁止个性化推荐，false-不禁止；true-禁止
     */
    @WireField(
            tag = 8,
            adapter = "com.squareup.wire.ProtoAdapter#BOOL"
    )
    public final Boolean disable_personalized_recommendation;

    /**
     * disable_personalized_recommendation 个性化状态（实时状态）与sdk初始化个性化推荐状态是否一致。false-一致；true-不一致
     */
    @WireField(
            tag = 9,
            adapter = "com.squareup.wire.ProtoAdapter#BOOL"
    )
    public final Boolean change_recommendation_state;

    public User(Integer yob, String gender, List<String> app_list, List<String> user_strategy,
                Version app_market_version, Boolean is_minor, Boolean disable_personalized_recommendation,
                Boolean change_recommendation_state) {
        this(yob, gender, app_list, user_strategy, app_market_version, is_minor, disable_personalized_recommendation, change_recommendation_state, ByteString.EMPTY);
    }

    public User(Integer yob, String gender, List<String> app_list, List<String> user_strategy,
                Version app_market_version, Boolean is_minor, Boolean disable_personalized_recommendation,
                Boolean change_recommendation_state, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.yob = yob;
        this.gender = gender;
        this.app_list = Internal.immutableCopyOf("app_list", app_list);
        this.user_strategy = Internal.immutableCopyOf("user_strategy", user_strategy);
        this.app_market_version = app_market_version;
        this.is_minor = is_minor;
        this.disable_personalized_recommendation = disable_personalized_recommendation;
        this.change_recommendation_state = change_recommendation_state;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.yob = yob;
        builder.gender = gender;
        builder.app_list = Internal.copyOf("app_list", app_list);
        builder.user_strategy = Internal.copyOf("user_strategy", user_strategy);
        builder.app_market_version = app_market_version;
        builder.is_minor = is_minor;
        builder.disable_personalized_recommendation = disable_personalized_recommendation;
        builder.change_recommendation_state = change_recommendation_state;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof User)) return false;
        User o = (User) other;
        return unknownFields().equals(o.unknownFields())
                && Internal.equals(yob, o.yob)
                && Internal.equals(gender, o.gender)
                && app_list.equals(o.app_list)
                && user_strategy.equals(o.user_strategy)
                && Internal.equals(app_market_version, o.app_market_version)
                && Internal.equals(is_minor, o.is_minor)
                && Internal.equals(disable_personalized_recommendation, o.disable_personalized_recommendation)
                && Internal.equals(change_recommendation_state, o.change_recommendation_state);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (yob != null ? yob.hashCode() : 0);
            result = result * 37 + (gender != null ? gender.hashCode() : 0);
            result = result * 37 + app_list.hashCode();
            result = result * 37 + user_strategy.hashCode();
            result = result * 37 + (app_market_version != null ? app_market_version.hashCode() : 0);
            result = result * 37 + (is_minor != null ? is_minor.hashCode() : 0);
            result = result * 37 + (disable_personalized_recommendation != null ? disable_personalized_recommendation.hashCode() : 0);
            result = result * 37 + (change_recommendation_state != null ? change_recommendation_state.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (yob != null) builder.append(", yob=").append(yob);
        if (gender != null) builder.append(", gender=").append(gender);
        if (!app_list.isEmpty()) builder.append(", app_list=").append(app_list);
        if (!user_strategy.isEmpty()) builder.append(", user_strategy=").append(user_strategy);
        if (app_market_version != null)
            builder.append(", app_market_version=").append(app_market_version);
        if (is_minor != null) builder.append(", is_minor=").append(is_minor);
        if (disable_personalized_recommendation != null)
            builder.append(", disable_personalized_recommendation=").append(disable_personalized_recommendation);
        if (change_recommendation_state != null)
            builder.append(", change_recommendation_state=").append(change_recommendation_state);
        return builder.replace(0, 2, "User{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<User, Builder> {
        public Integer yob = DEFAULT_YOB;

        public String gender = DEFAULT_GENDER;

        public List<String> app_list;

        public List<String> user_strategy;

        public Version app_market_version;

        public Boolean is_minor = DEFAULT_IS_MINOR;

        public Boolean disable_personalized_recommendation = DEFAULT_DISABLE_PERSONALIZED_RECOMMENDATION;

        public Boolean change_recommendation_state = DEFAULT_CHANGE_RECOMMENDATION_STATE;

        public Builder() {
            app_list = Internal.newMutableList();
            user_strategy = Internal.newMutableList();
        }

        /**
         * 生日年份，例：1995
         */
        public Builder yob(Integer yob) {
            this.yob = yob;
            return this;
        }

        /**
         * 性别，M-男；F-女；O-未知
         */
        public Builder gender(String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * 用户已安装应用列表
         */
        public Builder app_list(List<String> app_list) {
            Internal.checkElementsNotNull(app_list);
            this.app_list = app_list;
            return this;
        }

        /**
         * 用户属性id，如：3342，表示改用户安装了com.weibo应用；1111，表示该用户是体育运动爱好者
         */
        public Builder user_strategy(List<String> user_strategy) {
            Internal.checkElementsNotNull(user_strategy);
            this.user_strategy = user_strategy;
            return this;
        }

        /**
         * 设备应用市场版本号
         */
        public Builder app_market_version(Version app_market_version) {
            this.app_market_version = app_market_version;
            return this;
        }

        /**
         * 是否未成年人，false-否；true-是
         */
        public Builder is_minor(Boolean is_minor) {
            this.is_minor = is_minor;
            return this;
        }

        /**
         * 是否禁止个性化推荐，false-不禁止；true-禁止
         */
        public Builder disable_personalized_recommendation(Boolean disable_personalized_recommendation) {
            this.disable_personalized_recommendation = disable_personalized_recommendation;
            return this;
        }

        /**
         * disable_personalized_recommendation 个性化状态（实时状态）与sdk初始化个性化推荐状态是否一致。false-一致；true-不一致
         */
        public Builder change_recommendation_state(Boolean change_recommendation_state) {
            this.change_recommendation_state = change_recommendation_state;
            return this;
        }

        @Override
        public User build() {
            return new User(yob, gender, app_list, user_strategy, app_market_version, is_minor, disable_personalized_recommendation, change_recommendation_state, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_User extends ProtoAdapter<User> {
        public ProtoAdapter_User() {
            super(FieldEncoding.LENGTH_DELIMITED, User.class);
        }

        @Override
        public int encodedSize(User value) {
            return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.yob)
                    + ProtoAdapter.STRING.encodedSizeWithTag(2, value.gender)
                    + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.app_list)
                    + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.user_strategy)
                    + Version.ADAPTER.encodedSizeWithTag(5, value.app_market_version)
                    + ProtoAdapter.BOOL.encodedSizeWithTag(7, value.is_minor)
                    + ProtoAdapter.BOOL.encodedSizeWithTag(8, value.disable_personalized_recommendation)
                    + ProtoAdapter.BOOL.encodedSizeWithTag(9, value.change_recommendation_state)
                    + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, User value) throws IOException {
            ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.yob);
            ProtoAdapter.STRING.encodeWithTag(writer, 2, value.gender);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.app_list);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.user_strategy);
            Version.ADAPTER.encodeWithTag(writer, 5, value.app_market_version);
            ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_minor);
            ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.disable_personalized_recommendation);
            ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.change_recommendation_state);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public User decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.yob(ProtoAdapter.UINT32.decode(reader));
                        break;
                    case 2:
                        builder.gender(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 3:
                        builder.app_list.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 4:
                        builder.user_strategy.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 5:
                        builder.app_market_version(Version.ADAPTER.decode(reader));
                        break;
                    case 7:
                        builder.is_minor(ProtoAdapter.BOOL.decode(reader));
                        break;
                    case 8:
                        builder.disable_personalized_recommendation(ProtoAdapter.BOOL.decode(reader));
                        break;
                    case 9:
                        builder.change_recommendation_state(ProtoAdapter.BOOL.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public User redact(User value) {
            Builder builder = value.newBuilder();
            if (builder.app_market_version != null)
                builder.app_market_version = Version.ADAPTER.redact(builder.app_market_version);
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}